In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
a = np.arange(1, 21)
result = np.power(2, a) / a
result

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
a = np.arange(6)
array1 = np.power(0.1, 3 * a) 
array2= np.power(0.2, 4 * a)
result = np.dot(array1, array2)
result

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))
print('Cartesian\n', X)
X[:, 0] = np.sqrt(np.power(X[:, 0], 2) + np.power(X[:, 1], 2))
X[:, 1] = np.arctan2(X[:, 1], X[:, 0])
print('Polar\n', X)

Cartesian
 [[0.08261773 0.63119188]
 [0.4156034  0.07296644]
 [0.14205606 0.02946208]
 [0.85546833 0.06515394]
 [0.75188764 0.86733133]]
Polar
 [[0.6365759  0.78115134]
 [0.42196005 0.17122931]
 [0.14507908 0.20035153]
 [0.85794586 0.0757963 ]
 [1.14786701 0.64707716]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
print(X)
ind = np.argmax(X)
print('\nvalue: ', X.flat[ind], '\nindices: ', (ind // 10, ind % 10))

[[0.02990741 0.2023671  0.39524021 0.41382936 0.70321334 0.70969592
  0.8255645  0.26390412 0.21820859 0.27665513]
 [0.09562649 0.66311044 0.79461373 0.54122122 0.89679408 0.26637884
  0.77801157 0.57370291 0.88351889 0.01144902]
 [0.67681121 0.65566673 0.64106983 0.66412307 0.46047325 0.35193296
  0.66493347 0.09296227 0.1982284  0.80866017]
 [0.29292574 0.2672128  0.85289941 0.28969979 0.97603118 0.92546548
  0.72863319 0.50261524 0.12697395 0.1069463 ]
 [0.47685945 0.41616645 0.37843461 0.7088921  0.67097206 0.04206991
  0.55055024 0.506835   0.23055069 0.40162642]
 [0.03704503 0.63173696 0.01549513 0.72097942 0.16324975 0.59274683
  0.1130902  0.23769609 0.254167   0.8360232 ]
 [0.51298576 0.71166815 0.39806237 0.7858984  0.97881339 0.29027424
  0.57539161 0.51785019 0.59976701 0.07021021]
 [0.97572236 0.78241338 0.29753856 0.59918874 0.90232643 0.7403282
  0.98647496 0.85756847 0.31654331 0.75530551]
 [0.41535484 0.58195049 0.75022362 0.86542733 0.0523975  0.32505208
  0.07053419 

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
print('X:\n', X)
y = np.random.random((1, 2))
print('\ny:\n', y)
dist = np.sqrt(
    np.power((X[:, 0] - y[0, 0]), 2) + np.power((X[:, 1] - y[0, 1]), 2))
print('\ndistances:\n', dist)
print('\n nearest point:\n', X[np.argmin(dist)])

X:
 [[0.78378216 0.62552139]
 [0.50914945 0.14594378]
 [0.6779109  0.04856478]
 [0.635177   0.93522037]
 [0.48877481 0.81560957]
 [0.15451828 0.32672629]
 [0.99195216 0.7929786 ]
 [0.25238458 0.9393253 ]
 [0.50804695 0.94542374]
 [0.63159369 0.35787497]]

y:
 [[0.35170372 0.81899499]]

distances:
 [0.47341717 0.69122144 0.83664439 0.30637467 0.13711289 0.53029291
 0.64077681 0.1560246  0.20106575 0.53941641]

 nearest point:
 [0.48877481 0.81560957]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
@np.vectorize
def func(x):
    if x<0:
        return x**2 + 2 * x + 6
    elif x>=2:
        return x**2 + 4 * x - 4
    else:
        return x+6

x = np.linspace(-3, 3, 100)
func(x)

array([ 9.        ,  8.76124885,  8.52984389,  8.30578512,  8.08907254,
        7.87970615,  7.67768595,  7.48301194,  7.29568411,  7.11570248,
        6.94306703,  6.77777778,  6.61983471,  6.46923783,  6.32598714,
        6.19008264,  6.06152433,  5.94031221,  5.82644628,  5.71992654,
        5.62075298,  5.52892562,  5.44444444,  5.36730946,  5.29752066,
        5.23507805,  5.17998163,  5.1322314 ,  5.09182736,  5.05876951,
        5.03305785,  5.01469238,  5.00367309,  5.        ,  5.00367309,
        5.01469238,  5.03305785,  5.05876951,  5.09182736,  5.1322314 ,
        5.17998163,  5.23507805,  5.29752066,  5.36730946,  5.44444444,
        5.52892562,  5.62075298,  5.71992654,  5.82644628,  5.94031221,
        6.03030303,  6.09090909,  6.15151515,  6.21212121,  6.27272727,
        6.33333333,  6.39393939,  6.45454545,  6.51515152,  6.57575758,
        6.63636364,  6.6969697 ,  6.75757576,  6.81818182,  6.87878788,
        6.93939394,  7.        ,  7.06060606,  7.12121212,  7.18

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))
X = X - X.mean(axis=0)
print('Check result:\n', X.mean(axis=0))

Check result:
 [-5.55111512e-17 -7.77156117e-17 -9.99200722e-17 -1.11022302e-17
 -1.22124533e-16 -1.11022302e-17 -2.22044605e-17 -1.11022302e-16
  7.77156117e-17 -1.11022302e-17]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
print('expected value: ', np.mean(X), '\ndispersion: ', np.nanvar(X))

expected value:  4.9578084919934655 
dispersion:  4.148454298844579


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
np.indices((5, 5)).sum(axis = 0) % 5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0

    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1

        res.append(idx)
    return res


sample([50, 3, 1, 7, 20], 5)

[1, 0, 4, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [13]:
def new_sample(x, c):
    assert len(x) > 0

    indices = np.arange(0, len(x))
    prob = x / np.sum(x)
    return np.random.choice(indices, size=c, p=prob)


new_sample([50, 3, 1, 7, 20], 5)

array([0, 0, 4, 4, 0])