In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
a = np.arange(1, 21)
result = 2**a / a
result

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
a = np.arange(6)
array1 = np.power(0.1, 3 * a) 
array2= np.power(0.2, 4 * a)
result = np.dot(array1, array2)
result

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))
print('Cartesian\n', X)
X[:, 0] = np.sqrt(np.power(X[:, 0], 2) + np.power(X[:, 1], 2))
X[:, 1] = np.arctan2(X[:, 1], X[:, 0])
print('Polar\n', X)

Cartesian
 [[0.95184825 0.93192987]
 [0.61694268 0.6714371 ]
 [0.81591625 0.33370753]
 [0.93101323 0.42914057]
 [0.52959766 0.03028486]]
Polar
 [[1.33210674 0.61045141]
 [0.91183664 0.63471212]
 [0.88152144 0.36188689]
 [1.02515719 0.39644544]
 [0.53046287 0.05702948]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
print(X)
ind = np.argmax(X)
print('\nvalue: ', X.flat[ind], '\nindices: ', (ind // 10, ind % 10))

[[0.84028623 0.32284866 0.67404839 0.62509916 0.77628146 0.66046466
  0.90558423 0.84966537 0.69635525 0.74271554]
 [0.024951   0.02280258 0.66715453 0.55464652 0.78871621 0.94859241
  0.9981593  0.12830717 0.1676205  0.04172187]
 [0.93727445 0.46356678 0.24000656 0.62713589 0.77814125 0.91580072
  0.92137101 0.89699667 0.09696749 0.05865248]
 [0.83263705 0.12378737 0.10115491 0.33571362 0.6474436  0.7451206
  0.1798506  0.34169907 0.01371466 0.64361485]
 [0.70342585 0.8330002  0.46399924 0.34082237 0.57872779 0.9494897
  0.44315265 0.27923072 0.98267348 0.01257798]
 [0.01059512 0.25023911 0.7267694  0.27786442 0.07134297 0.10574634
  0.80434574 0.8115556  0.2296165  0.49752638]
 [0.87881946 0.47822701 0.24335541 0.11428651 0.1805999  0.61283346
  0.96584832 0.37722088 0.37499028 0.02230779]
 [0.11010923 0.87256744 0.20732499 0.71140081 0.46876891 0.31899128
  0.70177823 0.5748358  0.35396509 0.61622905]
 [0.34297776 0.30084974 0.32324626 0.29896092 0.62107324 0.20862114
  0.25901275 0

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
print('X:\n', X)
y = np.random.random((1, 2))
print('\ny:\n', y)
dist = np.sqrt(
    np.power((X[:, 0] - y[0, 0]), 2) + np.power((X[:, 1] - y[0, 1]), 2))
print('\ndistances:\n', dist)
print('\n nearest point:\n', X[np.argmin(dist)])

X:
 [[0.46790834 0.34903241]
 [0.40937686 0.33612754]
 [0.92087046 0.71070616]
 [0.543468   0.08068141]
 [0.76962272 0.64837641]
 [0.38722277 0.63259064]
 [0.36774091 0.27076538]
 [0.03901929 0.69076766]
 [0.80693335 0.54120791]
 [0.84664074 0.29912393]]

y:
 [[0.71834448 0.0754501 ]]

distances:
 [0.37089829 0.40424463 0.6667586  0.17495471 0.57521649 0.64811046
 0.40133642 0.91656883 0.47410792 0.25785638]

 nearest point:
 [0.543468   0.08068141]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
def func(x):
    if x<0:
        return x**2 + 2 * x + 6
    elif x>=2:
        return x**2 + 4 * x - 4
    else:
        return x+6

x = np.linspace(-3, 3, 100)
f = np.vectorize(func)
f(x)

array([ 9.        ,  8.76124885,  8.52984389,  8.30578512,  8.08907254,
        7.87970615,  7.67768595,  7.48301194,  7.29568411,  7.11570248,
        6.94306703,  6.77777778,  6.61983471,  6.46923783,  6.32598714,
        6.19008264,  6.06152433,  5.94031221,  5.82644628,  5.71992654,
        5.62075298,  5.52892562,  5.44444444,  5.36730946,  5.29752066,
        5.23507805,  5.17998163,  5.1322314 ,  5.09182736,  5.05876951,
        5.03305785,  5.01469238,  5.00367309,  5.        ,  5.00367309,
        5.01469238,  5.03305785,  5.05876951,  5.09182736,  5.1322314 ,
        5.17998163,  5.23507805,  5.29752066,  5.36730946,  5.44444444,
        5.52892562,  5.62075298,  5.71992654,  5.82644628,  5.94031221,
        6.03030303,  6.09090909,  6.15151515,  6.21212121,  6.27272727,
        6.33333333,  6.39393939,  6.45454545,  6.51515152,  6.57575758,
        6.63636364,  6.6969697 ,  6.75757576,  6.81818182,  6.87878788,
        6.93939394,  7.        ,  7.06060606,  7.12121212,  7.18

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))
X = X - X.mean(axis=0)
print('Check result:\n', X.mean(axis=0))

Check result:
 [-2.22044605e-17  2.22044605e-17 -1.11022302e-17  1.44328993e-16
  0.00000000e+00  3.33066907e-17  8.88178420e-17  2.22044605e-17
  1.05471187e-16  7.77156117e-17]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
print('expected value: ', np.mean(X), '\ndispersion: ', np.nanvar(X))

expected value:  5.061069579505634 
dispersion:  4.16030881112819


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
np.indices((5, 5)).sum(axis = 0) % 5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0

    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1

        res.append(idx)
    return res


sample([50, 3, 1, 7, 20], 5)

[4, 0, 1, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [13]:
def new_sample(x, c):
    assert len(x) > 0

    indices = np.arange(0, len(x))
    prob = x / np.sum(x)
    return np.random.choice(indices, size=c, p=prob)


new_sample([50, 3, 1, 7, 20], 5)

array([4, 0, 0, 0, 2])